import { chromium } from "@playwright/test";
const OUT = process.env.SHOT_DIR;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 950 } });
const p = await ctx.newPage();
p.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE " + m.text().slice(0, 120)); });
await p.goto("http://localhost:5173/login");
await p.waitForTimeout(1800);
await p.screenshot({ path: `${OUT}/new-login.png` });
console.log("signing in…");
await p.locator("#field-email").fill("employee@example.invalid");
await p.locator("#field-password").fill("innovation-2026");
await p.getByRole("button", { name: /^Sign in$/ }).click();
await p.waitForTimeout(2500);
console.log("URL " + p.url());
await p.screenshot({ path: `${OUT}/new-shell.png` });
await b.close();
